# Generated by Django 4.1.3 on 2026-04-07 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=500, unique=True)),
                ('client', models.CharField(max_length=100)),
                ('regex', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='PatternLayoutMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payor', models.CharField(max_length=100)),
                ('layout_id', models.IntegerField()),
                ('datatype', models.CharField(max_length=100)),
                ('employergroup', models.CharField(max_length=100)),
                ('layouttype', models.CharField(max_length=100)),
                ('pattern', models.CharField(max_length=500)),
                ('addeddate', models.DateField(auto_now_add=True)),
                ('modifieddate', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TableLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=500, unique=True)),
                ('client', models.CharField(max_length=100)),
                ('regex', models.CharField(max_length=500)),
            ],
        ),
    ]
