# Generated by Django 4.1.3 on 2026-04-10 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patternapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tablelog',
            name='regex',
        ),
        migrations.AddField(
            model_name='patternlayoutmapping',
            name='cuttingfloor',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='tablelog',
            name='cuttingfloor',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
